export const DEFAULT_PERMISSIONS = [
  { action: 'manage', subject: 'all', description: 'Full access to all tenant resources' },
  { action: 'manage', subject: 'tenant', description: 'Manage tenant settings' },
  { action: 'manage', subject: 'users', description: 'Invite and manage users' },
  { action: 'read', subject: 'users', description: 'View tenant users and directory profiles' },
  { action: 'manage', subject: 'roles', description: 'Manage roles and permissions' },
  { action: 'read', subject: 'roles', description: 'View roles and permission assignments' },
  { action: 'manage', subject: 'workspaces', description: 'Manage workspaces' },
  { action: 'read', subject: 'workspaces', description: 'View workspaces' },
  { action: 'manage', subject: 'teams', description: 'Manage teams' },
  { action: 'read', subject: 'teams', description: 'View teams and team membership' },
  { action: 'manage', subject: 'projects', description: 'Manage projects' },
  { action: 'read', subject: 'projects', description: 'View projects' },
  { action: 'manage', subject: 'tasks', description: 'Manage tasks' },
  { action: 'read', subject: 'tasks', description: 'View tasks' },
  { action: 'comment', subject: 'tasks', description: 'Comment on tasks' },
  { action: 'manage', subject: 'sprints', description: 'Plan, start, complete, and manage sprints' },
  { action: 'read', subject: 'sprints', description: 'View sprint planning and sprint reports' },
  { action: 'manage', subject: 'meetings', description: 'Create, update, cancel, and manage tenant meetings' },
  { action: 'read', subject: 'meetings', description: 'View tenant meetings and meeting details' },
  { action: 'manage', subject: 'files', description: 'Upload, link, archive, and manage files' },
  { action: 'read', subject: 'files', description: 'View file metadata and attachments' },
  { action: 'manage', subject: 'docs', description: 'Create, publish, archive, and manage workspace documents' },
  { action: 'read', subject: 'docs', description: 'View workspace documents' },
  { action: 'manage', subject: 'mail', description: 'Manage internal mailboxes, aliases, and mailbox members' },
  { action: 'read', subject: 'mail', description: 'Use internal mail in the tenant workspace' },
  { action: 'manage', subject: 'approvals', description: 'Create approval definitions and manage approval workflows' },
  { action: 'read', subject: 'approvals', description: 'View approval requests and approval history' },
  { action: 'manage', subject: 'workflows', description: 'Create, run, and manage workflow automation' },
  { action: 'read', subject: 'workflows', description: 'View workflow automation and run history' },
  { action: 'manage', subject: 'reports', description: 'Manage reports and dashboards' },
  { action: 'read', subject: 'reports', description: 'View reports and dashboards' },
  { action: 'manage', subject: 'ai', description: 'Manage AI assistants and tenant AI controls' },
  { action: 'read', subject: 'ai', description: 'Use AI assistants and view AI conversations' },
  { action: 'manage', subject: 'billing', description: 'Manage billing and subscriptions' },
  { action: 'read', subject: 'billing', description: 'View billing plan and subscription state' },
  { action: 'manage', subject: 'integrations', description: 'Manage integrations and webhooks' },
  { action: 'read', subject: 'integrations', description: 'View integrations and sync status' },
  { action: 'manage', subject: 'notifications', description: 'Manage tenant notification templates and delivery' },
  { action: 'read', subject: 'notifications', description: 'View and manage personal notifications' },
  { action: 'read', subject: 'audit_logs', description: 'View audit logs' },
  { action: 'manage', subject: 'security', description: 'Manage security policies, sessions, events, and API keys' },
  { action: 'read', subject: 'security', description: 'View security posture, sessions, events, and API keys' },
  { action: 'manage', subject: 'compliance', description: 'Manage compliance workflows and retention policies' },
  { action: 'read', subject: 'compliance', description: 'View compliance workflows and retention status' }
] as const;

export const DEFAULT_ROLES = [
  {
    name: 'Owner',
    description: 'Tenant owner with full administrative access',
    permissions: ['manage:all']
  },
  {
    name: 'Admin',
    description: 'Organization administrator',
    permissions: [
      'manage:tenant',
      'manage:users',
      'manage:roles',
      'manage:workspaces',
      'manage:teams',
      'manage:projects',
      'manage:tasks',
      'manage:sprints',
      'manage:meetings',
      'manage:files',
      'manage:docs',
      'manage:mail',
      'manage:approvals',
      'manage:workflows',
      'manage:reports',
      'manage:ai',
      'manage:billing',
      'manage:integrations',
      'manage:notifications',
      'read:audit_logs',
      'manage:security',
      'manage:compliance'
    ]
  },
  {
    name: 'Project Manager',
    description: 'Project delivery owner',
    permissions: [
      'read:users',
      'read:roles',
      'read:workspaces',
      'read:teams',
      'read:projects',
      'manage:projects',
      'read:tasks',
      'manage:tasks',
      'read:sprints',
      'manage:sprints',
      'read:meetings',
      'manage:meetings',
      'read:files',
      'manage:files',
      'read:docs',
      'manage:docs',
      'read:approvals',
      'manage:approvals',
      'read:workflows',
      'read:reports',
      'read:ai',
      'read:notifications'
    ]
  },
  {
    name: 'Team Lead',
    description: 'Team-level work manager',
    permissions: [
      'read:users',
      'read:roles',
      'read:workspaces',
      'read:teams',
      'read:projects',
      'read:tasks',
      'manage:tasks',
      'comment:tasks',
      'read:sprints',
      'manage:sprints',
      'read:meetings',
      'manage:meetings',
      'read:files',
      'manage:files',
      'read:docs',
      'read:approvals',
      'read:reports',
      'read:ai',
      'read:notifications'
    ]
  },
  {
    name: 'Member',
    description: 'Standard contributor',
    permissions: [
      'read:users',
      'read:roles',
      'read:workspaces',
      'read:teams',
      'read:projects',
      'read:tasks',
      'comment:tasks',
      'read:sprints',
      'read:meetings',
      'read:files',
      'read:docs',
      'read:reports',
      'read:ai',
      'read:mail',
      'read:notifications'
    ]
  },
  {
    name: 'Developer',
    description: 'Delivery contributor focused on board and task execution',
    permissions: [
      'read:users',
      'read:roles',
      'read:workspaces',
      'read:teams',
      'read:projects',
      'read:tasks',
      'comment:tasks',
      'read:sprints',
      'read:meetings',
      'read:files',
      'manage:files',
      'read:docs',
      'read:reports',
      'read:ai',
      'read:mail',
      'read:notifications'
    ]
  },
  {
    name: 'QA Tester',
    description: 'Quality contributor for testing, review, and verification work',
    permissions: [
      'read:users',
      'read:roles',
      'read:workspaces',
      'read:teams',
      'read:projects',
      'read:tasks',
      'comment:tasks',
      'read:sprints',
      'read:meetings',
      'read:files',
      'manage:files',
      'read:docs',
      'read:reports',
      'read:ai',
      'read:mail',
      'read:notifications'
    ]
  },
  {
    name: 'Scrum Master',
    description: 'Sprint facilitator with planning, board, and team coordination access',
    permissions: [
      'read:users',
      'read:roles',
      'read:workspaces',
      'read:teams',
      'read:projects',
      'read:tasks',
      'manage:tasks',
      'comment:tasks',
      'read:sprints',
      'manage:sprints',
      'read:meetings',
      'manage:meetings',
      'read:files',
      'read:docs',
      'read:approvals',
      'read:workflows',
      'read:reports',
      'read:ai',
      'read:mail',
      'read:notifications'
    ]
  },
  {
    name: 'Client',
    description: 'External project stakeholder',
    permissions: [
      'read:users',
      'read:roles',
      'read:workspaces',
      'read:teams',
      'read:projects',
      'read:tasks',
      'read:meetings',
      'comment:tasks',
      'read:files',
      'read:docs',
      'read:notifications'
    ]
  },
  {
    name: 'Guest',
    description: 'Limited read-only collaborator',
    permissions: [
      'read:users',
      'read:roles',
      'read:workspaces',
      'read:teams',
      'read:projects',
      'read:tasks',
      'read:meetings',
      'read:files',
      'read:docs',
      'read:notifications'
    ]
  }
] as const;

export const permissionKey = (permission: { action: string; subject: string }) =>
  `${permission.action}:${permission.subject}`;

export const AUTH_REFRESH_COOKIE = 'taskbricks.refresh';
export const AUTH_TRUSTED_DEVICE_COOKIE = 'taskbricks.trusted_device';
